### ISSUE TITLE
Please give me the git repository of ZOOM-React-Native-Integration

### ISSUE THREAD

**Issue by ramanguptazelhus** [majirosstefan/ZOOM-React-Native-Integration#1]
Hi Sir,
I'm integrating the ZOOM-React-Native in my project from one month , so please give me link of your repository.

Thanks

**Comment by majirosstefan** [comment]
Hello @ramanguptazelhus,

the blog posts  / tutorials are here:  
* https://stefan-majiros.com/blog/integrating-zoom-sdk-into-react-native-v-63-4-complete-tutorial-ios/ 
* https://stefan-majiros.com/blog/integrating-zoom-sdk-into-react-native/

They also contain links to repo - https://bitbucket.org/majirosstefan/zoom-react-native-example/src/main/

**Comment by ramanguptazelhus** [comment]
Thanks @majirosstefan  for replying but I have tried
ZoomExampleRN is not working,it gives lots of errors

**Comment by majirosstefan** [comment]
Feel free to create / submit new PRs.

**Comment by ramanguptazelhus** [comment]
This is the repo (https://github.com/ramangupta1602/ZoomExampleRN.git),
please take the latest pull from the master branch.

Thanks

**Comment by ramangupta1602** [comment]
I have cloned your repository and solved so many errors. but I'm stuck at preparing meeting.... screen after  using meeting number and password,please take the latest pull from the master branch.(https://github.com/ramangupta1602/ZoomExample.git) and add your android downloaded folder.
![Screenshot_1692275505](https://github.com/majirosstefan/ZOOM-React-Native-Integration/assets/73559449/22e1dbe5-4f78-448f-a2a5-bc7b71912855)
![Screenshot_1692275490](https://github.com/majirosstefan/ZOOM-React-Native-Integration/assets/73559449/78980156-55f2-48c6-9282-f1d29a41054a)

**Comment by ramangupta1602** [comment]
**meetingClientIncompatible** got this error when I joined Zoom meeting
